version: "3.8"
services:
  postgres:
    image: postgres:14
    restart: always
    container_name: piiano
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - piiano:/var/lib/postgresql/data
volumes:
  piiano:
