/**
 * Piiano Vault REST API
 * --- sidebar_position: 1 sidebar_label: Overview slug: / ---  # Introduction  The Piiano Vault REST API enables you to access and manage collections, objects, tokens, users, policies, and other resources within Piiano Vault in a simple, programmatic way using conventional HTTP requests and standard HTTP response codes.  The API follows RESTful conventions when possible, with most operations performed by `GET`, `POST`, `PUT`, `PATCH`, and `DELETE` requests. Request and response bodies are [JSON-encoded](https://www.json.org/json-en.html). However, for collection operations, an SQL-like [PVSchema](/guides/manage-collections-and-schemas/reference/pvschema) encoding is available.  This API reference provides details for each operation available in the API.  When you install a local copy of Vault, you can try each operation using **Send API request**.  An OpenAPI specification is available in [YAML](@site/static/assets/openapi.yaml) and [JSON](@site/static/assets/openapi.json) formats and can be used to generate client code for the API. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthPolicy model module.
 * @module model/AuthPolicy
 * @version 1.0
 */
class AuthPolicy {
    /**
     * Constructs a new <code>AuthPolicy</code>.
     * @alias module:model/AuthPolicy
     * @param operations {Array.<String>} 
     * @param policyType {String} 
     * @param reasons {Array.<String>} 
     * @param resources {Array.<String>} 
     */
    constructor(operations, policyType, reasons, resources) { 
        
        AuthPolicy.initialize(this, operations, policyType, reasons, resources);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, operations, policyType, reasons, resources) { 
        obj['operations'] = operations;
        obj['policyType'] = policyType;
        obj['reasons'] = reasons;
        obj['resources'] = resources;
    }

    /**
     * Constructs a <code>AuthPolicy</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthPolicy} obj Optional instance to populate.
     * @return {module:model/AuthPolicy} The populated <code>AuthPolicy</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthPolicy();

            if (data.hasOwnProperty('operations')) {
                obj['operations'] = ApiClient.convertToType(data['operations'], ['String']);
            }
            if (data.hasOwnProperty('policyType')) {
                obj['policyType'] = ApiClient.convertToType(data['policyType'], 'String');
            }
            if (data.hasOwnProperty('reasons')) {
                obj['reasons'] = ApiClient.convertToType(data['reasons'], ['String']);
            }
            if (data.hasOwnProperty('resources')) {
                obj['resources'] = ApiClient.convertToType(data['resources'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} operations
 */
AuthPolicy.prototype['operations'] = undefined;

/**
 * @member {String} policyType
 */
AuthPolicy.prototype['policyType'] = undefined;

/**
 * @member {Array.<String>} reasons
 */
AuthPolicy.prototype['reasons'] = undefined;

/**
 * @member {Array.<String>} resources
 */
AuthPolicy.prototype['resources'] = undefined;






export default AuthPolicy;

