/**
 * Piiano Vault REST API
 * --- sidebar_position: 1 sidebar_label: Overview slug: / ---  # Introduction  The Piiano Vault REST API enables you to access and manage collections, objects, tokens, users, policies, and other resources within Piiano Vault in a simple, programmatic way using conventional HTTP requests and standard HTTP response codes.  The API follows RESTful conventions when possible, with most operations performed by `GET`, `POST`, `PUT`, `PATCH`, and `DELETE` requests. Request and response bodies are [JSON-encoded](https://www.json.org/json-en.html). However, for collection operations, an SQL-like [PVSchema](/guides/manage-collections-and-schemas/reference/pvschema) encoding is available.  This API reference provides details for each operation available in the API.  When you install a local copy of Vault, you can try each operation using **Send API request**.  An OpenAPI specification is available in [YAML](@site/static/assets/openapi.yaml) and [JSON](@site/static/assets/openapi.json) formats and can be used to generate client code for the API. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AuthPolicy from './AuthPolicy';
import AuthRole from './AuthRole';
import AuthUser from './AuthUser';

/**
 * The AuthConfig model module.
 * @module model/AuthConfig
 * @version 1.0
 */
class AuthConfig {
    /**
     * Constructs a new <code>AuthConfig</code>.
     * @alias module:model/AuthConfig
     * @param policies {Object.<String, module:model/AuthPolicy>} 
     * @param roles {Object.<String, module:model/AuthRole>} 
     * @param users {Object.<String, module:model/AuthUser>} 
     */
    constructor(policies, roles, users) { 
        
        AuthConfig.initialize(this, policies, roles, users);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, policies, roles, users) { 
        obj['policies'] = policies;
        obj['roles'] = roles;
        obj['users'] = users;
    }

    /**
     * Constructs a <code>AuthConfig</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthConfig} obj Optional instance to populate.
     * @return {module:model/AuthConfig} The populated <code>AuthConfig</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthConfig();

            if (data.hasOwnProperty('policies')) {
                obj['policies'] = ApiClient.convertToType(data['policies'], {'String': AuthPolicy});
            }
            if (data.hasOwnProperty('roles')) {
                obj['roles'] = ApiClient.convertToType(data['roles'], {'String': AuthRole});
            }
            if (data.hasOwnProperty('users')) {
                obj['users'] = ApiClient.convertToType(data['users'], {'String': AuthUser});
            }
        }
        return obj;
    }


}

/**
 * @member {Object.<String, module:model/AuthPolicy>} policies
 */
AuthConfig.prototype['policies'] = undefined;

/**
 * @member {Object.<String, module:model/AuthRole>} roles
 */
AuthConfig.prototype['roles'] = undefined;

/**
 * @member {Object.<String, module:model/AuthUser>} users
 */
AuthConfig.prototype['users'] = undefined;






export default AuthConfig;

