/**
 * Piiano Vault REST API
 * --- sidebar_position: 1 sidebar_label: Overview slug: / ---  # Introduction  The Piiano Vault REST API enables you to access and manage collections, objects, tokens, users, policies, and other resources within Piiano Vault in a simple, programmatic way using conventional HTTP requests and standard HTTP response codes.  The API follows RESTful conventions when possible, with most operations performed by `GET`, `POST`, `PUT`, `PATCH`, and `DELETE` requests. Request and response bodies are [JSON-encoded](https://www.json.org/json-en.html). However, for collection operations, an SQL-like [PVSchema](/guides/manage-collections-and-schemas/reference/pvschema) encoding is available.  This API reference provides details for each operation available in the API.  When you install a local copy of Vault, you can try each operation using **Send API request**.  An OpenAPI specification is available in [YAML](@site/static/assets/openapi.yaml) and [JSON](@site/static/assets/openapi.json) formats and can be used to generate client code for the API. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ConfigLog model module.
 * @module model/ConfigLog
 * @version 1.0
 */
class ConfigLog {
    /**
     * Constructs a new <code>ConfigLog</code>.
     * @alias module:model/ConfigLog
     * @param customerEnv {String} 
     * @param customerIdentifier {String} 
     * @param datadogApmEnable {Boolean} 
     * @param datadogEnable {Boolean} 
     * @param datadogEnv {String} 
     * @param level {String} 
     */
    constructor(customerEnv, customerIdentifier, datadogApmEnable, datadogEnable, datadogEnv, level) { 
        
        ConfigLog.initialize(this, customerEnv, customerIdentifier, datadogApmEnable, datadogEnable, datadogEnv, level);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, customerEnv, customerIdentifier, datadogApmEnable, datadogEnable, datadogEnv, level) { 
        obj['customer_env'] = customerEnv;
        obj['customer_identifier'] = customerIdentifier;
        obj['datadog_apm_enable'] = datadogApmEnable;
        obj['datadog_enable'] = datadogEnable;
        obj['datadog_env'] = datadogEnv;
        obj['level'] = level;
    }

    /**
     * Constructs a <code>ConfigLog</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConfigLog} obj Optional instance to populate.
     * @return {module:model/ConfigLog} The populated <code>ConfigLog</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConfigLog();

            if (data.hasOwnProperty('customer_env')) {
                obj['customer_env'] = ApiClient.convertToType(data['customer_env'], 'String');
            }
            if (data.hasOwnProperty('customer_identifier')) {
                obj['customer_identifier'] = ApiClient.convertToType(data['customer_identifier'], 'String');
            }
            if (data.hasOwnProperty('datadog_apm_enable')) {
                obj['datadog_apm_enable'] = ApiClient.convertToType(data['datadog_apm_enable'], 'Boolean');
            }
            if (data.hasOwnProperty('datadog_enable')) {
                obj['datadog_enable'] = ApiClient.convertToType(data['datadog_enable'], 'Boolean');
            }
            if (data.hasOwnProperty('datadog_env')) {
                obj['datadog_env'] = ApiClient.convertToType(data['datadog_env'], 'String');
            }
            if (data.hasOwnProperty('level')) {
                obj['level'] = ApiClient.convertToType(data['level'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} customer_env
 */
ConfigLog.prototype['customer_env'] = undefined;

/**
 * @member {String} customer_identifier
 */
ConfigLog.prototype['customer_identifier'] = undefined;

/**
 * @member {Boolean} datadog_apm_enable
 */
ConfigLog.prototype['datadog_apm_enable'] = undefined;

/**
 * @member {Boolean} datadog_enable
 */
ConfigLog.prototype['datadog_enable'] = undefined;

/**
 * @member {String} datadog_env
 */
ConfigLog.prototype['datadog_env'] = undefined;

/**
 * @member {String} level
 */
ConfigLog.prototype['level'] = undefined;






export default ConfigLog;

