/**
 * Piiano Vault REST API
 * --- sidebar_position: 1 sidebar_label: Overview slug: / ---  # Introduction  The Piiano Vault REST API enables you to access and manage collections, objects, tokens, users, policies, and other resources within Piiano Vault in a simple, programmatic way using conventional HTTP requests and standard HTTP response codes.  The API follows RESTful conventions when possible, with most operations performed by `GET`, `POST`, `PUT`, `PATCH`, and `DELETE` requests. Request and response bodies are [JSON-encoded](https://www.json.org/json-en.html). However, for collection operations, an SQL-like [PVSchema](/guides/manage-collections-and-schemas/reference/pvschema) encoding is available.  This API reference provides details for each operation available in the API.  When you install a local copy of Vault, you can try each operation using **Send API request**.  An OpenAPI specification is available in [YAML](@site/static/assets/openapi.yaml) and [JSON](@site/static/assets/openapi.json) formats and can be used to generate client code for the API. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ConfigTLS model module.
 * @module model/ConfigTLS
 * @version 1.0
 */
class ConfigTLS {
    /**
     * Constructs a new <code>ConfigTLS</code>.
     * @alias module:model/ConfigTLS
     * @param certFile {String} 
     * @param enable {Boolean} 
     * @param keyFile {String} 
     * @param selfsigned {Boolean} 
     */
    constructor(certFile, enable, keyFile, selfsigned) { 
        
        ConfigTLS.initialize(this, certFile, enable, keyFile, selfsigned);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, certFile, enable, keyFile, selfsigned) { 
        obj['cert_file'] = certFile;
        obj['enable'] = enable;
        obj['key_file'] = keyFile;
        obj['selfsigned'] = selfsigned;
    }

    /**
     * Constructs a <code>ConfigTLS</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConfigTLS} obj Optional instance to populate.
     * @return {module:model/ConfigTLS} The populated <code>ConfigTLS</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConfigTLS();

            if (data.hasOwnProperty('cert_file')) {
                obj['cert_file'] = ApiClient.convertToType(data['cert_file'], 'String');
            }
            if (data.hasOwnProperty('enable')) {
                obj['enable'] = ApiClient.convertToType(data['enable'], 'Boolean');
            }
            if (data.hasOwnProperty('key_file')) {
                obj['key_file'] = ApiClient.convertToType(data['key_file'], 'String');
            }
            if (data.hasOwnProperty('selfsigned')) {
                obj['selfsigned'] = ApiClient.convertToType(data['selfsigned'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} cert_file
 */
ConfigTLS.prototype['cert_file'] = undefined;

/**
 * @member {Boolean} enable
 */
ConfigTLS.prototype['enable'] = undefined;

/**
 * @member {String} key_file
 */
ConfigTLS.prototype['key_file'] = undefined;

/**
 * @member {Boolean} selfsigned
 */
ConfigTLS.prototype['selfsigned'] = undefined;






export default ConfigTLS;

