/**
 * Piiano Vault REST API
 * --- sidebar_position: 1 sidebar_label: Overview slug: / ---  # Introduction  The Piiano Vault REST API enables you to access and manage collections, objects, tokens, users, policies, and other resources within Piiano Vault in a simple, programmatic way using conventional HTTP requests and standard HTTP response codes.  The API follows RESTful conventions when possible, with most operations performed by `GET`, `POST`, `PUT`, `PATCH`, and `DELETE` requests. Request and response bodies are [JSON-encoded](https://www.json.org/json-en.html). However, for collection operations, an SQL-like [PVSchema](/guides/manage-collections-and-schemas/reference/pvschema) encoding is available.  This API reference provides details for each operation available in the API.  When you install a local copy of Vault, you can try each operation using **Send API request**.  An OpenAPI specification is available in [YAML](@site/static/assets/openapi.yaml) and [JSON](@site/static/assets/openapi.json) formats and can be used to generate client code for the API. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ConfigFeatures model module.
 * @module model/ConfigFeatures
 * @version 1.0
 */
class ConfigFeatures {
    /**
     * Constructs a new <code>ConfigFeatures</code>.
     * @alias module:model/ConfigFeatures
     * @param apiKeyHashing {Boolean} 
     * @param encryption {Boolean} 
     * @param policyEnforcement {Boolean} 
     * @param maskLicense {Boolean} 
     * @param customTypesEnable {Boolean} 
     */
    constructor(apiKeyHashing, encryption, policyEnforcement, maskLicense, customTypesEnable) { 
        
        ConfigFeatures.initialize(this, apiKeyHashing, encryption, policyEnforcement, maskLicense, customTypesEnable);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, apiKeyHashing, encryption, policyEnforcement, maskLicense, customTypesEnable) { 
        obj['api_key_hashing'] = apiKeyHashing;
        obj['encryption'] = encryption;
        obj['policy_enforcement'] = policyEnforcement;
        obj['mask_license'] = maskLicense;
        obj['custom_types_enable'] = customTypesEnable;
    }

    /**
     * Constructs a <code>ConfigFeatures</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConfigFeatures} obj Optional instance to populate.
     * @return {module:model/ConfigFeatures} The populated <code>ConfigFeatures</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConfigFeatures();

            if (data.hasOwnProperty('api_key_hashing')) {
                obj['api_key_hashing'] = ApiClient.convertToType(data['api_key_hashing'], 'Boolean');
            }
            if (data.hasOwnProperty('encryption')) {
                obj['encryption'] = ApiClient.convertToType(data['encryption'], 'Boolean');
            }
            if (data.hasOwnProperty('policy_enforcement')) {
                obj['policy_enforcement'] = ApiClient.convertToType(data['policy_enforcement'], 'Boolean');
            }
            if (data.hasOwnProperty('mask_license')) {
                obj['mask_license'] = ApiClient.convertToType(data['mask_license'], 'Boolean');
            }
            if (data.hasOwnProperty('custom_types_enable')) {
                obj['custom_types_enable'] = ApiClient.convertToType(data['custom_types_enable'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} api_key_hashing
 */
ConfigFeatures.prototype['api_key_hashing'] = undefined;

/**
 * @member {Boolean} encryption
 */
ConfigFeatures.prototype['encryption'] = undefined;

/**
 * @member {Boolean} policy_enforcement
 */
ConfigFeatures.prototype['policy_enforcement'] = undefined;

/**
 * @member {Boolean} mask_license
 */
ConfigFeatures.prototype['mask_license'] = undefined;

/**
 * @member {Boolean} custom_types_enable
 */
ConfigFeatures.prototype['custom_types_enable'] = undefined;






export default ConfigFeatures;

