/**
 * Piiano Vault REST API
 * --- sidebar_position: 1 sidebar_label: Overview slug: / ---  # Introduction  The Piiano Vault REST API enables you to access and manage collections, objects, tokens, users, policies, and other resources within Piiano Vault in a simple, programmatic way using conventional HTTP requests and standard HTTP response codes.  The API follows RESTful conventions when possible, with most operations performed by `GET`, `POST`, `PUT`, `PATCH`, and `DELETE` requests. Request and response bodies are [JSON-encoded](https://www.json.org/json-en.html). However, for collection operations, an SQL-like [PVSchema](/guides/manage-collections-and-schemas/reference/pvschema) encoding is available.  This API reference provides details for each operation available in the API.  When you install a local copy of Vault, you can try each operation using **Send API request**.  An OpenAPI specification is available in [YAML](@site/static/assets/openapi.yaml) and [JSON](@site/static/assets/openapi.json) formats and can be used to generate client code for the API. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ModelsAPIKey model module.
 * @module model/ModelsAPIKey
 * @version 1.0
 */
class ModelsAPIKey {
    /**
     * Constructs a new <code>ModelsAPIKey</code>.
     * @alias module:model/ModelsAPIKey
     * @param apiKey {String} The new API key generated for the user.
     * @param apiKeyExpiry {Date} The expiry time of the API key.
     */
    constructor(apiKey, apiKeyExpiry) { 
        
        ModelsAPIKey.initialize(this, apiKey, apiKeyExpiry);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, apiKey, apiKeyExpiry) { 
        obj['api_key'] = apiKey;
        obj['api_key_expiry'] = apiKeyExpiry;
    }

    /**
     * Constructs a <code>ModelsAPIKey</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelsAPIKey} obj Optional instance to populate.
     * @return {module:model/ModelsAPIKey} The populated <code>ModelsAPIKey</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelsAPIKey();

            if (data.hasOwnProperty('api_key')) {
                obj['api_key'] = ApiClient.convertToType(data['api_key'], 'String');
            }
            if (data.hasOwnProperty('api_key_expiry')) {
                obj['api_key_expiry'] = ApiClient.convertToType(data['api_key_expiry'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * The new API key generated for the user.
 * @member {String} api_key
 */
ModelsAPIKey.prototype['api_key'] = undefined;

/**
 * The expiry time of the API key.
 * @member {Date} api_key_expiry
 */
ModelsAPIKey.prototype['api_key_expiry'] = undefined;






export default ModelsAPIKey;

