/**
 * Piiano Vault REST API
 * --- sidebar_position: 1 sidebar_label: Overview slug: / ---  # Introduction  The Piiano Vault REST API enables you to access and manage collections, objects, tokens, users, policies, and other resources within Piiano Vault in a simple, programmatic way using conventional HTTP requests and standard HTTP response codes.  The API follows RESTful conventions when possible, with most operations performed by `GET`, `POST`, `PUT`, `PATCH`, and `DELETE` requests. Request and response bodies are [JSON-encoded](https://www.json.org/json-en.html). However, for collection operations, an SQL-like [PVSchema](/guides/manage-collections-and-schemas/reference/pvschema) encoding is available.  This API reference provides details for each operation available in the API.  When you install a local copy of Vault, you can try each operation using **Send API request**.  An OpenAPI specification is available in [YAML](@site/static/assets/openapi.yaml) and [JSON](@site/static/assets/openapi.json) formats and can be used to generate client code for the API. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ModelsVaultGeneration from './ModelsVaultGeneration';
import ModelsWorker from './ModelsWorker';

/**
 * The ModelsAllGenerations model module.
 * @module model/ModelsAllGenerations
 * @version 1.0
 */
class ModelsAllGenerations {
    /**
     * Constructs a new <code>ModelsAllGenerations</code>.
     * @alias module:model/ModelsAllGenerations
     * @param vault {module:model/ModelsVaultGeneration} 
     * @param workers {Array.<module:model/ModelsWorker>} Workers generations.
     */
    constructor(vault, workers) { 
        
        ModelsAllGenerations.initialize(this, vault, workers);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, vault, workers) { 
        obj['vault'] = vault;
        obj['workers'] = workers;
    }

    /**
     * Constructs a <code>ModelsAllGenerations</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelsAllGenerations} obj Optional instance to populate.
     * @return {module:model/ModelsAllGenerations} The populated <code>ModelsAllGenerations</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelsAllGenerations();

            if (data.hasOwnProperty('vault')) {
                obj['vault'] = ModelsVaultGeneration.constructFromObject(data['vault']);
            }
            if (data.hasOwnProperty('workers')) {
                obj['workers'] = ApiClient.convertToType(data['workers'], [ModelsWorker]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ModelsVaultGeneration} vault
 */
ModelsAllGenerations.prototype['vault'] = undefined;

/**
 * Workers generations.
 * @member {Array.<module:model/ModelsWorker>} workers
 */
ModelsAllGenerations.prototype['workers'] = undefined;






export default ModelsAllGenerations;

