/**
 * Piiano Vault REST API
 * --- sidebar_position: 1 sidebar_label: Overview slug: / ---  # Introduction  The Piiano Vault REST API enables you to access and manage collections, objects, tokens, users, policies, and other resources within Piiano Vault in a simple, programmatic way using conventional HTTP requests and standard HTTP response codes.  The API follows RESTful conventions when possible, with most operations performed by `GET`, `POST`, `PUT`, `PATCH`, and `DELETE` requests. Request and response bodies are [JSON-encoded](https://www.json.org/json-en.html). However, for collection operations, an SQL-like [PVSchema](/guides/manage-collections-and-schemas/reference/pvschema) encoding is available.  This API reference provides details for each operation available in the API.  When you install a local copy of Vault, you can try each operation using **Send API request**.  An OpenAPI specification is available in [YAML](@site/static/assets/openapi.yaml) and [JSON](@site/static/assets/openapi.json) formats and can be used to generate client code for the API. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ModelsTransformation model module.
 * @module model/ModelsTransformation
 * @version 1.0
 */
class ModelsTransformation {
    /**
     * Constructs a new <code>ModelsTransformation</code>.
     * Details of a transformation that can be performed on a PII data type within a collection.
     * @alias module:model/ModelsTransformation
     * @param name {String} The name of the transformation.
     * @param piiTypeName {String} The name of the PII type to which the transformation can be applied.
     */
    constructor(name, piiTypeName) { 
        
        ModelsTransformation.initialize(this, name, piiTypeName);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, piiTypeName) { 
        obj['name'] = name;
        obj['pii_type_name'] = piiTypeName;
    }

    /**
     * Constructs a <code>ModelsTransformation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelsTransformation} obj Optional instance to populate.
     * @return {module:model/ModelsTransformation} The populated <code>ModelsTransformation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelsTransformation();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('pii_type_name')) {
                obj['pii_type_name'] = ApiClient.convertToType(data['pii_type_name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The name of the transformation.
 * @member {String} name
 */
ModelsTransformation.prototype['name'] = undefined;

/**
 * The name of the PII type to which the transformation can be applied.
 * @member {String} pii_type_name
 */
ModelsTransformation.prototype['pii_type_name'] = undefined;






export default ModelsTransformation;

