/**
 * Piiano Vault REST API
 * --- sidebar_position: 1 sidebar_label: Overview slug: / ---  # Introduction  The Piiano Vault REST API enables you to access and manage collections, objects, tokens, users, policies, and other resources within Piiano Vault in a simple, programmatic way using conventional HTTP requests and standard HTTP response codes.  The API follows RESTful conventions when possible, with most operations performed by `GET`, `POST`, `PUT`, `PATCH`, and `DELETE` requests. Request and response bodies are [JSON-encoded](https://www.json.org/json-en.html). However, for collection operations, an SQL-like [PVSchema](/guides/manage-collections-and-schemas/reference/pvschema) encoding is available.  This API reference provides details for each operation available in the API.  When you install a local copy of Vault, you can try each operation using **Send API request**.  An OpenAPI specification is available in [YAML](@site/static/assets/openapi.yaml) and [JSON](@site/static/assets/openapi.json) formats and can be used to generate client code for the API. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ModelsTokenAggregatedMetadata from './ModelsTokenAggregatedMetadata';
import ModelsTokenRefMetadata from './ModelsTokenRefMetadata';

/**
 * The ModelsTokenMetadata model module.
 * @module model/ModelsTokenMetadata
 * @version 1.0
 */
class ModelsTokenMetadata {
    /**
     * Constructs a new <code>ModelsTokenMetadata</code>.
     * @alias module:model/ModelsTokenMetadata
     * @param agg {module:model/ModelsTokenAggregatedMetadata} 
     * @param reusableTokenId {Boolean} Whether the token ID can be reused.
     * @param reversible {Boolean} Whether the tokens are reversible.
     * @param scope {String} The scope of the tokens.
     * @param tokenId {String} The shared ID of the tokens.
     * @param tokens {Array.<module:model/ModelsTokenRefMetadata>} The metadata for each token.
     */
    constructor(agg, reusableTokenId, reversible, scope, tokenId, tokens) { 
        
        ModelsTokenMetadata.initialize(this, agg, reusableTokenId, reversible, scope, tokenId, tokens);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, agg, reusableTokenId, reversible, scope, tokenId, tokens) { 
        obj['agg'] = agg;
        obj['reusable_token_id'] = reusableTokenId;
        obj['reversible'] = reversible;
        obj['scope'] = scope;
        obj['token_id'] = tokenId;
        obj['tokens'] = tokens;
    }

    /**
     * Constructs a <code>ModelsTokenMetadata</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelsTokenMetadata} obj Optional instance to populate.
     * @return {module:model/ModelsTokenMetadata} The populated <code>ModelsTokenMetadata</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelsTokenMetadata();

            if (data.hasOwnProperty('agg')) {
                obj['agg'] = ModelsTokenAggregatedMetadata.constructFromObject(data['agg']);
            }
            if (data.hasOwnProperty('reusable_token_id')) {
                obj['reusable_token_id'] = ApiClient.convertToType(data['reusable_token_id'], 'Boolean');
            }
            if (data.hasOwnProperty('reversible')) {
                obj['reversible'] = ApiClient.convertToType(data['reversible'], 'Boolean');
            }
            if (data.hasOwnProperty('scope')) {
                obj['scope'] = ApiClient.convertToType(data['scope'], 'String');
            }
            if (data.hasOwnProperty('token_id')) {
                obj['token_id'] = ApiClient.convertToType(data['token_id'], 'String');
            }
            if (data.hasOwnProperty('tokens')) {
                obj['tokens'] = ApiClient.convertToType(data['tokens'], [ModelsTokenRefMetadata]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ModelsTokenAggregatedMetadata} agg
 */
ModelsTokenMetadata.prototype['agg'] = undefined;

/**
 * Whether the token ID can be reused.
 * @member {Boolean} reusable_token_id
 */
ModelsTokenMetadata.prototype['reusable_token_id'] = undefined;

/**
 * Whether the tokens are reversible.
 * @member {Boolean} reversible
 */
ModelsTokenMetadata.prototype['reversible'] = undefined;

/**
 * The scope of the tokens.
 * @member {String} scope
 */
ModelsTokenMetadata.prototype['scope'] = undefined;

/**
 * The shared ID of the tokens.
 * @member {String} token_id
 */
ModelsTokenMetadata.prototype['token_id'] = undefined;

/**
 * The metadata for each token.
 * @member {Array.<module:model/ModelsTokenRefMetadata>} tokens
 */
ModelsTokenMetadata.prototype['tokens'] = undefined;






export default ModelsTokenMetadata;

