/**
 * Piiano Vault REST API
 * --- sidebar_position: 1 sidebar_label: Overview slug: / ---  # Introduction  The Piiano Vault REST API enables you to access and manage collections, objects, tokens, users, policies, and other resources within Piiano Vault in a simple, programmatic way using conventional HTTP requests and standard HTTP response codes.  The API follows RESTful conventions when possible, with most operations performed by `GET`, `POST`, `PUT`, `PATCH`, and `DELETE` requests. Request and response bodies are [JSON-encoded](https://www.json.org/json-en.html). However, for collection operations, an SQL-like [PVSchema](/guides/manage-collections-and-schemas/reference/pvschema) encoding is available.  This API reference provides details for each operation available in the API.  When you install a local copy of Vault, you can try each operation using **Send API request**.  An OpenAPI specification is available in [YAML](@site/static/assets/openapi.yaml) and [JSON](@site/static/assets/openapi.json) formats and can be used to generate client code for the API. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ModelsRotatedToken model module.
 * @module model/ModelsRotatedToken
 * @version 1.0
 */
class ModelsRotatedToken {
    /**
     * Constructs a new <code>ModelsRotatedToken</code>.
     * @alias module:model/ModelsRotatedToken
     * @param newTokenId {String} The ID of the token.
     * @param oldTokenId {String} The ID of the token before rotation.
     */
    constructor(newTokenId, oldTokenId) { 
        
        ModelsRotatedToken.initialize(this, newTokenId, oldTokenId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, newTokenId, oldTokenId) { 
        obj['new_token_id'] = newTokenId;
        obj['old_token_id'] = oldTokenId;
    }

    /**
     * Constructs a <code>ModelsRotatedToken</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelsRotatedToken} obj Optional instance to populate.
     * @return {module:model/ModelsRotatedToken} The populated <code>ModelsRotatedToken</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelsRotatedToken();

            if (data.hasOwnProperty('new_token_id')) {
                obj['new_token_id'] = ApiClient.convertToType(data['new_token_id'], 'String');
            }
            if (data.hasOwnProperty('old_token_id')) {
                obj['old_token_id'] = ApiClient.convertToType(data['old_token_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The ID of the token.
 * @member {String} new_token_id
 */
ModelsRotatedToken.prototype['new_token_id'] = undefined;

/**
 * The ID of the token before rotation.
 * @member {String} old_token_id
 */
ModelsRotatedToken.prototype['old_token_id'] = undefined;






export default ModelsRotatedToken;

