/**
 * Piiano Vault REST API
 * --- sidebar_position: 1 sidebar_label: Overview slug: / ---  # Introduction  The Piiano Vault REST API enables you to access and manage collections, objects, tokens, users, policies, and other resources within Piiano Vault in a simple, programmatic way using conventional HTTP requests and standard HTTP response codes.  The API follows RESTful conventions when possible, with most operations performed by `GET`, `POST`, `PUT`, `PATCH`, and `DELETE` requests. Request and response bodies are [JSON-encoded](https://www.json.org/json-en.html). However, for collection operations, an SQL-like [PVSchema](/guides/manage-collections-and-schemas/reference/pvschema) encoding is available.  This API reference provides details for each operation available in the API.  When you install a local copy of Vault, you can try each operation using **Send API request**.  An OpenAPI specification is available in [YAML](@site/static/assets/openapi.yaml) and [JSON](@site/static/assets/openapi.json) formats and can be used to generate client code for the API. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RestHTTPError model module.
 * @module model/RestHTTPError
 * @version 1.0
 */
class RestHTTPError {
    /**
     * Constructs a new <code>RestHTTPError</code>.
     * @alias module:model/RestHTTPError
     * @param context {Object.<String, String>} The error context.
     * @param errorCode {String} The error code.
     * @param message {String} The error message.
     */
    constructor(context, errorCode, message) { 
        
        RestHTTPError.initialize(this, context, errorCode, message);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, context, errorCode, message) { 
        obj['context'] = context;
        obj['error_code'] = errorCode;
        obj['message'] = message;
    }

    /**
     * Constructs a <code>RestHTTPError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RestHTTPError} obj Optional instance to populate.
     * @return {module:model/RestHTTPError} The populated <code>RestHTTPError</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RestHTTPError();

            if (data.hasOwnProperty('context')) {
                obj['context'] = ApiClient.convertToType(data['context'], {'String': 'String'});
            }
            if (data.hasOwnProperty('error_code')) {
                obj['error_code'] = ApiClient.convertToType(data['error_code'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The error context.
 * @member {Object.<String, String>} context
 */
RestHTTPError.prototype['context'] = undefined;

/**
 * The error code.
 * @member {String} error_code
 */
RestHTTPError.prototype['error_code'] = undefined;

/**
 * The error message.
 * @member {String} message
 */
RestHTTPError.prototype['message'] = undefined;






export default RestHTTPError;

