import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Button } from "@mantine/core";

export default function Home() {
	const launchDemo = () => {
		window.location.href = "/demo/";
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Piiano x Permit</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.mainTitle}>
				<h1 className={styles.title}>
					<span>Welcome to </span>
					<a href="https://piiano.com/" id="piiano">
						Piiano
					</a>
					<span> x </span>
					<a href="https://www.permit.io/" id="permit">
						Permit
					</a>
					<span> Demo</span>
				</h1>

				<Button
					color="green"
					onClick={() => launchDemo()}
					style={{ width: "280px", marginTop: "40px" }}
				>
					Start Demo
				</Button>
			</main>
		</div>
	);
}
